FROM alpine
RUN mkdir -p /var/lib/postgresql && chown postgres.postgres /var/lib/postgresql && apk update && apk add readline libxml2 krb5-libs gettext libldap tzdata && mkdir /postgres && cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime
COPY entrypoint.sh /
